#!/bin/sh

# This work is licensed under the Creative Commons 
# Attribution-NonCommercial-ShareAlike 3.0 France License. 
# To view a copy of this license, visit 
# http://creativecommons.org/licenses/by-nc-sa/3.0/fr/ 
# or send a letter to Creative Commons, 444 Castro Street, 
# Suite 900, Mountain View, California, 94041, USA.
# Author: younes.cheikh@gmail.com


VERSION=1.0

print_usage() {
  print_about
  echo "Usage : " 
  echo "$0 [-|+] [value]"
  echo "$0 [value] "
  echo "$0 [mute | unmute]" 
  echo "------------------------------------------------------------"
  print_examples

}

print_examples() {
  echo 
  echo "Examples: "
  echo "$0 - 10 \t\t -- decrease sound of 10% "
  echo "$0 + 18 \t\t -- increase sound of 18% "
  echo "$0 45 \t\t\t -- set sound to 45% "
  echo "$0 mute \t\t -- mute sound "
  echo "$0 unmute \t\t -- unmute sound "
}

print_about() {
  echo "------------------------------------------------------------"
  echo "csound: Simple command line sound controler for alsa devices"
  echo "https://github.com/cyounes/csound" 
  echo "------------------------------------------------------------"
  echo 
}

print_version() {
  echo $VERSION
}

if [ $# -eq 1 ]
then
  if [ "$1" = "mute" ]
  then
    amixer -D pulse set Master mute
  elif [ "$1" = "unmute" ]
  then
    amixer -D pulse set Master unmute
  elif [ "$1" = "-h" ] || [ "$1" = "--help" ] 
  then
    print_usage
  elif [ "$1" = "-v" ] || [ "$1" = "--version" ]
  then 
    print_version 
  else
    if [ $1 -ge 0 ] && [ $1 -le 100 ] 
    then
      amixer -D pulse set Master $1% unmute
    else
      print_usage
    fi
  fi
elif [ $# -eq 2 ]
then
  if [ "$1" = "+" ] || [ "$1" = "-" ] 
  then
    if [ $2 -ge 0 ] && [ $2 -le 100 ]
    then 
      amixer -D pulse set Master $2%$1 unmute
    fi
  fi
else
  print_usage
fi


