#!/bin/sh

# This work is licensed under the Creative Commons 
# Attribution-NonCommercial-ShareAlike 3.0 France License. 
# To view a copy of this license, visit 
# http://creativecommons.org/licenses/by-nc-sa/3.0/fr/ 
# or send a letter to Creative Commons, 444 Castro Street, 
# Suite 900, Mountain View, California, 94041, USA.
# Author: Cheikh Younes <younes.cheikh@gmail.com> http://cyounes.com


VERSION=1.0

print_usage() {
  print_about
  echo "Usage : 
${0##*/} [-|+] [value]
${0##*/} [value]
${0##*/} [mute | unmute]" 
  echo "------------------------------------------------------------"
  print_examples

}

print_examples() {
  echo 
  echo "Examples:
${0##*/} - 10 \t- decrease sound of 10%
${0##*/} + 18 \t- increase sound of 18%
${0##*/} 45 \t- set sound to 45%
${0##*/} mute \t- mute sound
${0##*/} unmute  \t- unmute sound "
}

print_about() {
  echo "------------------------------------------------------------"
  echo "csound: Simple command line sound controler for alsa devices"
  echo "https://github.com/cyounes/csound" 
  echo "------------------------------------------------------------"
  echo 
}

print_version() {
  echo $VERSION
}

if [ $# -eq 1 ]
then
  case $1 in
    "--mute"|"-m"|"mute") amixer -D pulse set Master mute
      ;;
    "--unmute"|"-u"|"unmute") amixer -D pulse set Master unmute
      ;;
    "-h"|"--help"|"help") print_usage
      ;;
    "-v"|"--version"|"version") print_version
      ;;
    *) 
      if [ $1 -ge 0 ] && [ $1 -le 100 ] 
      then
        amixer -D pulse set Master $1% unmute
      else
        print_usage
    fi
      ;;
  esac
elif [ $# -eq 2 ]
then
  if ( [ "$1" = "+" ] || [ "$1" = "-" ] ) && ( [ $2 -ge 0 ] && [ $2 -le 100 ] ) 
  then 
    amixer -D pulse set Master $2%$1 unmute
  fi
else
  print_usage
fi

# End of File
